name = "stillmind-auth"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "development"

[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "auth_tokens_dev"
preview_id = "auth_tokens_preview"

[env.production]
name = "stillmind-auth-prod"

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.kv_namespaces]]
binding = "AUTH_TOKENS"
id = "auth_tokens_prod"

# Add your email service API key as a secret:
# wrangler secret put EMAIL_API_KEY
# wrangler secret put JWT_SECRET